In [1]:
import numpy as np

In [17]:
vec = np.array([1,2,3,4], dtype = np.int32)
vec1 = np.array([5,6,7,8], dtype = np.int32)
vec2 = np.array([[1],[2],[3],[4]], dtype = np.int32)

mat = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = np.int32)
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype = np.int32)
mat2 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = np.int32)


In [3]:
vec * vec1

array([ 5, 12, 21, 32], dtype=int32)

In [4]:
vec * vec2

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]], dtype=int32)

In [18]:
mat * mat2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [19]:
vec * vec1

array([ 5, 12, 21, 32], dtype=int32)

In [21]:
temp = np.array([[1],[2],[3]])

In [29]:
temp = np.array([[1,1],[2,2],[3,3]])

In [25]:
temp

array([[1, 1],
       [2, 2],
       [3, 3]])

In [28]:
temp1 = np.array([[1,1,1],[2,2,2]])

In [27]:
temp

array([[1, 1, 1],
       [2, 2, 2]])

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 